version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_telegram_bot
    # restart: always
    env_file:
      - path: ./.env
    volumes:
      - .:/app
      - ~/.cache/huggingface/hub:/root/.cache/huggingface/hub
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

